### ISSUE TITLE
workmanager build failed, works with flutter

### ISSUE THREAD

**Issue by mihalycsaba** [Flutter-Foundation/nest#12]
I have switched with fvm, but I couldn't start my app, tried `fvm clean`, but didn't help. Switching back to flutter works.

```
e: /ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/BackgroundWorker.kt: (14, 44): Unresolved reference: shim
e: /ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/BackgroundWorker.kt: (98, 68): Unresolved reference: ShimPluginRegistry
e: /ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt: (35, 52): Unresolved reference: PluginRegistrantCallback
e: /ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt: (38, 52): Unresolved reference: Registrar
e: /ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt: (49, 80): Unresolved reference: PluginRegistrantCallback

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':workmanager:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

**Comment by matthew-carroll** [comment]
Hm, this is a strange issue. This looks very Android-centric.

So you tried running your app with `fvm flutter pub get` followed by `fvm flutter run`?

Can you please provide the output from `fvm flutter --version`?

**Comment by mihalycsaba** [comment]
I have rerun these commands, because the first time I run them through vscode, but I still get the same errors. The source value 8 warnings are unrelated, because I get them in flutter too. Only the workmanager errors are relevant.

```
fvm flutter --version
Flutter 3.27.0-1.0.pre.388 • channel master • https://github.com/Flutter-Foundation/flutter.git
Framework • revision 1ac0e968e4 (22 hours ago) • 2024-11-01 12:35:48 +0000
Engine • revision 0a0d5c9be6
Tools • Dart 3.7.0 (build 3.7.0-91.0.dev) • DevTools 2.40.1

flutter clean
Deleting build...                                                   74ms
Deleting .dart_tool...                                               2ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting ephemeral...                                                1ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms

fvm flutter pub get
Resolving dependencies... 
Downloading packages... 
  async 2.11.0 (2.12.0 available)
  boolean_selector 2.1.1 (2.1.2 available)
  characters 1.3.0 (1.3.1 available)
  clock 1.1.1 (1.1.2 available)
  collection 1.19.0 (1.19.1 available)
  csslib 0.17.3 (1.0.2 available)
  fake_async 1.3.1 (1.3.2 available)
  html 0.15.4 (0.15.5 available)
  http_parser 4.0.2 (4.1.1 available)
  lints 5.0.0 (5.1.0 available)
  matcher 0.12.16+1 (0.12.17 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  path 1.9.0 (1.9.1 available)
  shelf 1.4.1 (1.4.2 available)
  string_scanner 1.3.0 (1.4.0 available)
  vector_graphics 1.1.12 (1.1.13 available)
  vm_service 14.3.0 (14.3.1 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

fvm flutter run
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/BackgroundWorker.kt:14:44 Unresolved reference 'shim'.
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/BackgroundWorker.kt:98:55 Unresolved reference 'registerWith'.
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/BackgroundWorker.kt:98:68 Unresolved reference 'ShimPluginRegistry'.
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt:35:52 Unresolved reference 'PluginRegistrantCallback'.
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt:38:52 Unresolved reference 'Registrar'.
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt:40:49 Unresolved reference 'context'.
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt:40:70 Unresolved reference 'messenger'.
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt:41:23 Unresolved reference 'addViewDestroyListener'.
e: file:///ssd2/csaba/.pub-cache/hosted/pub.dev/workmanager-0.5.2/android/src/main/kotlin/dev/fluttercommunity/workmanager/WorkmanagerPlugin.kt:49:80 Unresolved reference 'PluginRegistrantCallback'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':workmanager:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 32s
Running Gradle task 'assembleDebug'...                             32.7s
Error: Gradle task assembleDebug failed with exit code 1

```

**Comment by matthew-carroll** [comment]
So those workmanager errors seem to be suggesting that some of Flutter's Android classes don't exist. That's pretty odd.

I think I'll have to try creating a project that uses workmanager, myself, and see if I can repro this error.

**Comment by elias8** [comment]
Maybe try using the latest update directly from git like below. For some reason the these changes are not deployed on pub dot dev.

```yaml
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
```

**Comment by mihalycsaba** [comment]
@elias8 I get the same errors.

@matthew-carroll could this be because of fvm? I have searched this reference errors. As far as I can tell this happens when the build system can't find the flutter sdk/engine.

I have never used fvm, I always work with the latest version. Once I needed an older version, but I did it without fvm. Would be nice if someone tried to reproduce this, I don't have anything unusual related to workmanager in my android configs. Could be some other issue with my gradle settings. I did configure newer than the default gradle, agp and kotlin versions.

Can I use flock without fvm? Not sure what fvm does and if it's necessary. I will also try to make a sample project with workmanager soon.

**Comment by mihalycsaba** [comment]
I have made a sample repo, this app throws the same error https://github.com/mihalycsaba/workmanager_test

**Comment by elias8** [comment]
I looked into the issue in detail and it is coming from the `workmanager` package depending on a missing class `io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry`, which allowed `old plugins use the new Android embedding and plugin API behind the scenes.` 

The `io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry` is removed from the engine when the [v1 embedding was completely removed](https://github.com/flutter/engine/pull/51229) on master. So the issue doesn't concern this or the flutter repo. I suggest creating an issue on the workmanager package. The current implementation of the package supports both v1 and v2 embeddings and it seems flutter will completely drop v1 support in the next releases.

**Comment by matthew-carroll** [comment]
@elias8 thanks for that careful analysis and update. @mihalycsaba based on that response, if you're able to determine that this isn't a Flock bug, please go ahead and close this issue. If you find additional evidence that this is caused by Flock or FVM, please feel free to provide that.

**Comment by mihalycsaba** [comment]
@elias8 thanks for the investigation. Can I do something quick to enable the v2 embeddings?

Anyway I will be closing.

**Comment by mihalycsaba** [comment]
here is my flutter version
```
flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (10 days ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

```
Tried it again it's so weird it builds if I start it from the UI, but fails when I run `flutter run`. Is there a separate cache for vscode?

**Comment by elias8** [comment]
If you have another version of Flutter installed or are using multiple versions of Flutter with fvm, use `fvm flutter run`.

**Comment by mihalycsaba** [comment]
@elias8 I only have one version of flutter.  I was just pointing out, that running the that test app from vscode(pressing f5) the app managed to build, but running `flutter run` failed which is weird. 

But anyway, getting the package from git resolves this. I have no idea why it didn't work the first time I tried. 

Now the package what I tried first builds successfully. But it turns off my monitor and crashes the emulator.  This has never happened before. I'm using linux, I think it crashed the graphic driver somehow.

```
fvm flutter run
Can't load Kernel binary: Invalid kernel binary format version.
FINE: Pub 3.7.0-91.0.dev
FINE: Package Config up to date.
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...                             21.4s
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...          859ms
I/flutter ( 4631): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
I/flutter ( 4631): dynamic_color: Core palette detected.
Syncing files to device sdk gphone64 x86 64...                     120ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on sdk gphone64 x86 64 is available at: http://127.0.0.1:46473/mVReFwsWf70=/
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:46473/mVReFwsWf70=/
E/FlutterJNI( 4631): Failed to decode image
E/FlutterJNI( 4631): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:254)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1981)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1973)
E/FlutterJNI( 4631):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:561)
D/ProfileInstaller( 4631): Installing profile for com.example.sg_ng
E/FlutterJNI( 4631): Failed to decode image
E/FlutterJNI( 4631): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:254)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1981)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1973)
E/FlutterJNI( 4631):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:561)

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:7332:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:7138:12)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2478:60)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:147:15)
#4      ImageLoader.loadImageAsync.<anonymous closure> (package:cached_network_image/src/image_provider/_image_loader.dart:65:22)
<asynchronous suspension>
#5      ImageLoader._load (package:cached_network_image/src/image_provider/_image_loader.dart:124:27)
<asynchronous suspension>
#6      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:26:7)
<asynchronous suspension>

Image provider:
  CachedNetworkImageProvider("https://steamcdn-a.akamaihd.net/steam/apps/1316760/capsule_184x69.jpg",
  scale: 1.0)
Image key:
  CachedNetworkImageProvider("https://steamcdn-a.akamaihd.net/steam/apps/1316760/capsule_184x69.jpg",
  scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

E/androidemu( 4631): Logging hang event. Number of tasks already hung: 0
E/androidemu( 4631): Metadata:
E/androidemu( 4631):     file: device/generic/goldfish-opengl/system/vulkan_enc/VkEncoder.cpp
E/androidemu( 4631):     function: vkCreateFence
E/androidemu( 4631):     line: 4294
E/androidemu( 4631):     msg: vkCreateFence in VkEncoder
E/androidemu( 4631):     thread: 4717 (0x0000126d)
E/androidemu( 4631):     process name: com.example.sg_ng
E/androidemu( 4631):     Additional information:
E/androidemu( 4631):             seqno: 4309
E/androidemu( 4631):             packetSize: 48
E/androidemu( 4631):             packetContents:  43 4E 00 00 30 00 00 00 D5 10 00 00 2E 00 00 00 05 00 03 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E/androidemu( 4631): Logging hang event. Number of tasks already hung: 1
E/androidemu( 4631): Metadata:
E/androidemu( 4631):     file: device/generic/goldfish-opengl/system/vulkan_enc/VkEncoder.cpp
E/androidemu( 4631):     function: vkGetFenceStatus
E/androidemu( 4631):     line: 4655
E/androidemu( 4631):     msg: vkGetFenceStatus in VkEncoder
E/androidemu( 4631):     thread: 4731 (0x0000127b)
E/androidemu( 4631):     process name: com.example.sg_ng
E/androidemu( 4631):     Additional information:
E/androidemu( 4631):             seqno: 4310
E/androidemu( 4631):             packetSize: 28
E/androidemu( 4631):             packetContents:  46 4E 00 00 1C 00 00 00 D6 10 00 00 2E 00 00 00 05 00 03 00 7F 08 00 00 17 00 16 00
E/androidemu( 4631): HealthMonitor: Number of unresponsive tasks increased: 0 -> 2
```

**Comment by mihalycsaba** [comment]
@elias8 I only have one version of flutter.  I was just pointing out, that running the that test app from vscode(pressing f5) the app managed to build, but running `flutter run` failed which is weird. 

But anyway, getting the package from git resolves this. I have no idea why it didn't work the first time I tried.
